### ISSUE TITLE
Changing s_texColor

### ISSUE THREAD

**Issue by SGoerzen** [DeepARSDK/quickstart-web-js#3]
Hello!

I have tried the background segmentation example in iOS and web. In iOS it is working well. But in web I have two issues:

1) Is already described here: https://github.com/DeepARSDK/quickstart-web-js/issues/1

2) I cannot change the galaxy texture on web. In swift I am using the `changeParameter` function and provide image. On web I tried to provide image and also tried to create a texture with below function, and provide the result to `changeParameter("Background", "MeshRenderer", "s_texColor", texture);`. 
How can I change a texture in web? 
Would it be possible to just get a function from DeepAR SDK which creates a compatible texture sampler?

E.g.

`const texture = deepAR.makeTexture(image);
deepAR.changeParameter("Background", "MeshRenderer", "s_texColor", texture);` 

or sth. like 
`deepAR.loadTexture("images/test.jpg", function(texture) {
 changeParameter("Background", "MeshRenderer", "s_texColor", texture);
});`

Function I used to create a texture sample:
`function _createTexture(gl,my_image) {
    const texture_object = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, texture_object);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
    gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, 1);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGB, gl.RGB, gl.UNSIGNED_BYTE, my_image);
    return texture_object;
  }`

**Comment by Sikter** [comment]
Hi, you are right we currently don't support setting the texture in HTML5 SDK, only scalar and vector values. However, the new SDK version is on it's way and it will support all the changeParameter variations one can use in iOS and  Android.

**Comment by SGoerzen** [comment]
Do you know when I can get access to the newer version? 

Kind of early access would be also fine to me (e.g. with some unfinished features), because next days I will only need background segmentation and use some AR effects.

**Comment by Sikter** [comment]
It's been some time, but for completeness, the requested functionality is now supported in HTML5 SDK since 2.0.0 version.
