### ISSUE TITLE
Apply web DeepAR on pictures instead of camera

### ISSUE THREAD

**Issue by SGoerzen** [DeepARSDK/quickstart-web-js#5]
Hello guys,

the background removal is working well! But the quality is still not satisfying enough for our use case.
In our tool we are using currently another removebg tool to remove the background serversided.

But we have on some AR filters the problem, that the removebg tool is not recognizing the Filters as important content, thus it removes them partially (e.g. Christmas moose horns get removed).

**Question: is it possible to apply DeepAR AR filters on pictures by Web SDK?**

The new workflow would be:
1) Use DeepAR as preview to take pictures (what is actually already done) on web
2) Turn of AR Filter before taking picture.
3) Capture picture over deepAR SDK.
3) Provide picture (without AR filter) to our background removal.
4) Turn on AR Filter on returned picture instead of camera in web frontend
5) Compose new picture
6) Further progress of our product

**Comment by JelenaKB** [comment]
Have a look at our image processing example it should do what you need.
