### ISSUE TITLE
DeepAR Web SDK in Electron JS desktop app

### ISSUE THREAD

**Issue by kevintd** [DeepARSDK/quickstart-web-js#9]
I want to test DeepAR Web SDK with Electron JS, it is working fine in the normal browser like Chrome but when I bring it to Electron then it has an error for loading deepar.wasm file from deepar.js sdk : 

Not allowed to load local resource: file:///D:/my_path/node_modules/electron/dist/resources/electron.asar/renderer/deepar.wasm
(anonymous) @ deepar.js:4245
(anonymous) @ deepar.js:4255
(anonymous) @ deepar.js:4257
DeepAR @ deepar.js:5445
(anonymous) @ cameraApp:536
cameraApp:1 Uncaught (in promise) TypeError: Failed to fetch

**Comment by JelenaKB** [comment]
Hi, the web SDK doesn't currently have electron support, it has to be run on a domain. We are planning electron support for the future .
